export type Language = 'EN' | 'KH';

export const translations: Record<Language, Record<string, string>> = {
  EN: {
    // Top Bar & App
    appName: "Riem Pawn & Loan Management System",
    branch: "Branch",
    searchPlaceholder: "Search ID, name or phone...",
    profile: "Profile",
    logout: "Log Out",
    login: "Log In",
    forgotPassword: "Forgot Password?",
    backToLogin: "Back to Login",
    sendResetLink: "Send Reset Link",
    welcomeBack: "Welcome Back",
    signInToContinue: "Sign in to access your dashboard",

    // Navigation Sidebar
    navDashboard: "Dashboard",
    navCustomers: "Customers",
    navPawnShop: "Pawn Shop",
    navLoans: "Loans",
    navInstallments: "Installments",
    navPayments: "Payments Center",
    navInventory: "Pawn Inventory",
    navAccounting: "Accounting",
    navReports: "Reports Module",
    navNotifications: "Reminder Alerts",
    navUsers: "User Management",
    navSettings: "Settings & Config",

    // Dashboard Items
    totalCustomers: "Total Customers",
    totalLoans: "Total Loans",
    totalPawnContracts: "Pawn Contracts",
    totalInstallments: "Installment Contracts",
    dailyIncome: "Daily Income",
    monthlyIncome: "Monthly Income",
    outstandingBalance: "O/S Balance",
    dueToday: "Due Today",
    overdueAccounts: "Overdue Accounts",
    recentTransactions: "Recent Transactions",
    revenueGrowth: "Revenue Comparison",
    loanStatusStats: "Loan Status Distribution",
    activePawnItems: "Pawn Categories",
    systemQuickStats: "System Overview",
    viewAll: "View All",

    // Common Actions / Buttons
    add: "Add New",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    save: "Save",
    cancel: "Cancel",
    actions: "Actions",
    search: "Search",
    status: "Status",
    print: "Print Receipt",
    renew: "Renew Interest",
    redeem: "Redeem Item",
    auction: "Auction Item",
    extend: "Extend Contract",
    pay: "Make Payment",
    success: "Success",
    warning: "Warning",
    error: "Error",
    info: "Info",

    // Customer Module
    customerId: "Customer ID",
    fullName: "Full Name",
    gender: "Gender",
    dob: "Date of Birth",
    nationalId: "National ID",
    phone: "Phone Number",
    address: "Address",
    occupation: "Occupation",
    emergencyContact: "Emergency Contact",
    emergencyName: "Contact Name",
    emergencyPhone: "Contact Phone",
    emergencyRelation: "Relation",
    photo: "Customer Photo",
    customerHistory: "Customer Dossier History",
    historyLoans: "Loan Records",
    historyPawns: "Pawn Records",
    historyPayments: "Payment Logs",

    // Pawn Module
    contractNo: "Contract No.",
    itemName: "Item Name",
    category: "Category",
    brand: "Brand",
    serialNo: "Serial / Chassis",
    estimatedValue: "Market Val (USD)",
    loanAmount: "Disbursed Amt (USD)",
    interestRate: "Interest Rate (%/mo)",
    pawnDate: "Pawn Date",
    expiryDate: "Expiry Date",
    storageLocation: "Shelf Location",
    extensionCount: "Extensions",
    
    // Categories
    Gold: "Gold (មាស)",
    Silver: "Silver (ប្រាក់)",
    Phone: "Smartphones (ទូរស័ព្ទ)",
    Laptop: "Computer/Laptop",
    Motorbike: "Motorbike (ម៉ូតូ)",
    Car: "Car / Vehicle",
    Electronics: "Electronics (គ្រឿងអគ្គិសនី)",
    Others: "Others",

    // Loan Module
    loanNo: "Loan No.",
    principal: "Principal",
    term: "Term (Months/Days)",
    startDate: "Start Date",
    endDate: "End Date",
    frequency: "Frequency",
    Daily: "Daily",
    Weekly: "Weekly",
    Monthly: "Monthly",
    Custom: "Custom Schedule",
    installmentNo: "No.",
    dueDate: "Due Date",
    amountDue: "Amount Due",
    paidAmount: "Paid Amount",
    remaining: "Remaining",
    paymentDate: "Payment Date",
    penalty: "Penalty",

    // Installments
    productName: "Product Name",
    productPrice: "Product Price",
    downPayment: "Down Payment",
    remainingBalance: "Financed Balance",
    termMonths: "Installment Term (mo)",
    monthlyInstallment: "Monthly Due",

    // Payments
    amount: "Amount",
    paymentMethod: "Payment Method",
    receiptNo: "Receipt No.",
    paymentType: "Payment Type",
    referenceId: "Ref Contract ID",
    currency: "Currency",
    cash: "Cash",
    bankTransfer: "Bank Transfer",
    khqr: "KHQR Pay",
    aba: "ABA Bank",
    acleda: "ACLEDA Bank",
    wing: "Wing Money",
    truemoney: "TrueMoney",
    collectedBy: "Collected By",
    notes: "Memo / Notes",

    // Accounting
    accountingModule: "Accounting Ledger",
    income: "Income Ledger",
    expense: "Expense Ledger",
    staffSalary: "Staff Salary",
    officeExpense: "Office Rent / Expense",
    utilities: "Utilities (Water/Electric)",
    maintenance: "Maintenance & IT",
    pawnInterest: "Pawn Interest",
    loanInterest: "Loan Interest",
    installmentProfit: "Installment Finance Income",
    lateFees: "Late Fee Charges",
    auctionIncome: "Auction Revenue",
    profitAndLoss: "Profit & Loss Statement",
    cashFlow: "Cash Flow Statement",
    totalIncome: "Total Revenues",
    totalExpense: "Total Expenses",
    netProfit: "Net Income",

    // Inventory
    storageStatus: "Storage Status",
    warehouse: "Vault / Warehouse",
    itemHistory: "Item Ledger Log",
    InStorage: "In Vault Store",
    Released: "Released / Redeemed",
    Auction: "Under Auction Sale",
    Lost: "Lost / Claim Processed",

    // Notifications
    reminderAlerts: "Trigger Alerts",
    dueReminder: "Due Reminders",
    overdueReminder: "Overdue Alerts",
    channels: "Send Channel",
    sendNotification: "Send Reminder Alert",
    telegram: "Telegram Bot Alert",
    sms: "SMS Cell Alert",
    email: "Email Dispatcher",

    // Users
    userManagement: "User Permissions & Activity",
    users: "Authorized Users",
    roles: "System Roles",
    activityLogs: "Security Audit Log",
    permissionList: "Access Matrix",
    SuperAdmin: "Super Admin",
    Admin: "Administrator",
    Manager: "Branch Manager",
    Staff: "General Staff",
    Accountant: "Accountant Officer",

    // Settings
    companySettings: "Company & Financial Setup",
    companyName: "Company Name",
    addressKh: "Address (Khmer)",
    addressEn: "Address (English)",
    phoneSetting: "Official Phone",
    emailSetting: "Official Email",
    defaultInterestRate: "Default Interest (%/mo)",
    penaltyRate: "Overdue Penalty (%/day)",
    dualCurrency: "Dual Currency USD/Riel",
    taxRate: "Corporate Tax Rate (%)",
    branchName: "Branch Name",
    backupDb: "Backup System Database",
    restoreDb: "Restore System Database",
  },
  KH: {
    // Top Bar & App
    appName: "ប្រព័ន្ធគ្រប់គ្រងការបញ្ចាំ កម្ចី និងបង់រំលស់ រៀម",
    branch: "សាខា",
    searchPlaceholder: "ស្វែងរកលេខកូដ ឈ្មោះ ឬលេខទូរស័ព្ទ...",
    profile: "គណនី",
    logout: "ចាកចេញ",
    login: "ចូលប្រើប្រាស់",
    forgotPassword: "ភ្លេចពាក្យសំងាត់?",
    backToLogin: "ត្រលប់មកទំព័រដើម",
    sendResetLink: "ផ្ញើតំណភ្ជាប់កំណត់ឡើងវិញ",
    welcomeBack: "សូមស្វាគមន៍",
    signInToContinue: "សូមចូលដើម្បីបន្តទៅកាន់ផ្ទាំងគ្រប់គ្រង",

    // Navigation Sidebar
    navDashboard: "ផ្ទាំងគ្រប់គ្រង",
    navCustomers: "អតិថិជន",
    navPawnShop: "ហាងបញ្ចាំ",
    navLoans: "ប្រព័ន្ធឥណទាន (កម្ចី)",
    navInstallments: "សេវាកម្មបង់រំលស់",
    navPayments: "បញ្ជរទូទាត់ប្រាក់",
    navInventory: "សារពើភ័ណ្ឌទំនិញបញ្ចាំ",
    navAccounting: "គណនេយ្យ",
    navReports: "របាយការណ៍សង្ខេប",
    navNotifications: "ប្រព័ន្ធជូនដំណឹង",
    navUsers: "បុគ្គលិក និងសិទ្ធិ",
    navSettings: "ការកំណត់ប្រព័ន្ធ",

    // Dashboard Items
    totalCustomers: "អតិថិជនសរុប",
    totalLoans: "កិច្ចសន្យាកម្ចីសរុប",
    totalPawnContracts: "កិច្ចសន្យាបញ្ចាំសរុប",
    totalInstallments: "កិច្ចសន្យារំលស់សរុប",
    dailyIncome: "ចំណូលប្រចាំថ្ងៃ",
    monthlyIncome: "ចំណូលប្រចាំខែ",
    outstandingBalance: "ឥណទានមិនទាន់ហូរចូល",
    dueToday: "ត្រូវបង់ប្រាក់ថ្ងៃនេះ",
    overdueAccounts: "គណនីហួសកាលកំណត់",
    recentTransactions: "ប្រតិបត្តិការចុងក្រោយ",
    revenueGrowth: "ការប្រៀបធៀបចំណូល",
    loanStatusStats: "ស្ថិតិនៃស្ថានភាពកម្ចី",
    activePawnItems: "ប្រភេទគ្រឿងបញ្ចាំសកម្ម",
    systemQuickStats: "ទិដ្ឋភាពទូទៅនៃប្រព័ន្ធ",
    viewAll: "មើលទាំងអស់",

    // Common Actions / Buttons
    add: "បង្កើតថ្មី",
    edit: "កែប្រែ",
    delete: "លុបចេញ",
    view: "មើលលម្អិត",
    save: "រក្សាទុក",
    cancel: "បដិសេធ",
    actions: "សកម្មភាព",
    search: "ស្វែងរក",
    status: "ស្ថានភាព",
    print: "បោះពុម្ពវិក្កយបត្រ",
    renew: "បន្តការប្រាក់បញ្ចាំ",
    redeem: "លោះគ្រឿងបញ្ចាំ",
    auction: "លក់ឡៃឡុង",
    extend: "ពន្យារកិច្ចសន្យា",
    pay: "បង់ប្រាក់ទូទាត់",
    success: "ជោគជ័យ",
    warning: "ព្រមាន",
    error: "កំហុស",
    info: "ព័ត៌មាន",

    // Customer Module
    customerId: "លេខសម្គាល់អតិថិជន",
    fullName: "ឈ្មោះពេញ",
    gender: "ភេទ",
    dob: "ថ្ងៃខែឆ្នាំកំណើត",
    nationalId: "អត្តសញ្ញាណប័ណ្ណ",
    phone: "លេខទូរស័ព្ទ",
    address: "អាសយដ្ឋាន",
    occupation: "មុខរបរ",
    emergencyContact: "ទំនាក់ទំនងបន្ទាន់",
    emergencyName: "ឈ្មោះអ្នកទាក់ទង",
    emergencyPhone: "លេខទូរស័ព្ទ",
    emergencyRelation: "ត្រូវជាអ្វីនឹងគ្នា",
    photo: "រូបថតអតិថិជន",
    customerHistory: "ប្រវត្តិកោសល្យវិច្ច័យអតិថិជន",
    historyLoans: "ប្រវត្តិកម្ចី",
    historyPawns: "ប្រវត្តិបញ្ចាំ",
    historyPayments: "ឯកសារទូទាត់ប្រាក់",

    // Pawn Module
    contractNo: "លេខកិច្ចសន្យា",
    itemName: "ឈ្មោះទំនិញ",
    category: "ប្រភេទគ្រឿងបញ្ចាំ",
    brand: "ម៉ាក/យីហោ",
    serialNo: "លេខម៉ាស៊ីន / លេខតួ",
    estimatedValue: "តម្លៃប៉ាន់ស្មាន (ដុល្លារ)",
    loanAmount: "ទំហំប្រាក់បញ្ចេញ (ដុល្លារ)",
    interestRate: "អត្រាការប្រាក់ (%/ខែ)",
    pawnDate: "ថ្ងៃបញ្ចាំ",
    expiryDate: "ថ្ងៃផុតកំណត់",
    storageLocation: "កន្លែងរក្សាទុក",
    extensionCount: "ចំនួនដងពន្យារ",

    // Categories
    Gold: "មាស / គ្រឿងអលង្ការ",
    Silver: "ប្រាក់ / គ្រឿងលំអ",
    Phone: "ទូរស័ព្ទដៃស្មាតហ្វូន",
    Laptop: "កុំព្យូទ័រ / ឡេបថប",
    Motorbike: "ម៉ូតូ / យានយន្តពីរគ្រាប់",
    Car: "រថយន្ត / យានយន្ត",
    Electronics: "គ្រឿងអគ្គិសនី / អេឡិចត្រូនិច",
    Others: "ផ្សេងៗទៀត",

    // Loan Module
    loanNo: "លេខកូដកម្ចី",
    principal: "ប្រាក់ដើមសរុប",
    term: "រយៈពេល (ខែ/ថ្ងៃ)",
    startDate: "ថ្ងៃចាប់ផ្តើម",
    endDate: "ថ្ងៃបញ្ចប់",
    frequency: "ប្រភេទការបង់ប្រាក់",
    Daily: "ប្រចាំថ្ងៃ",
    Weekly: "ប្រចាំសប្តាហ៍",
    Monthly: "ប្រចាំខែ",
    Custom: "កាលវិភាគកែច្នៃផ្ទាល់ខ្លួន",
    installmentNo: "ល.រ",
    dueDate: "ថ្ងៃត្រូវបង់ប្រាក់",
    amountDue: "ចំនួនត្រូវបង់",
    paidAmount: "ចំនួនបានបង់រួច",
    remaining: "ប្រាក់នៅសល់",
    paymentDate: "ថ្ងៃបានបង់",
    penalty: "ប្រាក់ពិន័យ",

    // Installments
    productName: "ឈ្មោះទំនិញរំលស់",
    productPrice: "តម្លៃទំនិញដើម",
    downPayment: "ប្រាក់កក់មុន",
    remainingBalance: "ប្រាក់ត្រូវរំលស់",
    termMonths: "រយៈពេលរំលស់ (ខែ)",
    monthlyInstallment: "ទឹកប្រាក់ត្រូវបង់ប្រចាំខែ",

    // Payments
    amount: "ទឹកប្រាក់",
    paymentMethod: "វិធីទូទាត់ប្រាក់",
    receiptNo: "លេខវិក្កយបត្រ",
    paymentType: "ប្រភេទការទូទាត់",
    referenceId: "លេខយោងកិច្ចសន្យា",
    currency: "រូបិយប័ណ្ណ",
    cash: "សាច់ប្រាក់ផ្ទាល់",
    bankTransfer: "ផ្ទេរប្រាក់តាមធនាគារ",
    khqr: "ស្កេន KHQR (ស្កេនទូទាត់)",
    aba: "ធនាគារ ABA",
    acleda: "ធនាគារ អេស៊ីលីដា",
    wing: "វីង (Wing)",
    truemoney: "ទ្រូម៉ានី (TrueMoney)",
    collectedBy: "អ្នកទទួលប្រាក់",
    notes: "កំណត់ចំណាំបន្ថែម",

    // Accounting
    accountingModule: "បញ្ជីគ្រប់គ្រងគណនេយ្យ",
    income: "គណនីប្រាក់ចំណូល",
    expense: "គណនីប្រាក់ចំណាយ",
    staffSalary: "ប្រាក់បៀវត្សរ៍បុគ្គលិក",
    officeExpense: "ការិយាល័យ និងធនធាន",
    utilities: "ទឹក ភ្លើង និងអ៊ីនធឺណិត",
    maintenance: "ការថែទាំ និងព័ត៌មានវិទ្យា",
    pawnInterest: "ចំណូលការប្រាក់បញ្ចាំ",
    loanInterest: "ចំណូលការប្រាក់កម្ចី",
    installmentProfit: "ចំណេញពីការលក់រំលស់",
    lateFees: "ការប្រាក់ពិន័យយឺតយ៉ាវ",
    auctionIncome: "ចំណូលលក់ឡៃឡុងគ្រឿងបញ្ចាំ",
    profitAndLoss: "របាយការណ៍ ចំណេញ ឬ ខាត",
    cashFlow: "រលំហូរសាច់ប្រាក់សង្ខេប",
    totalIncome: "ចំណូលសរុបទាំងអស់",
    totalExpense: "ចំណាយសរុបទាំងអស់",
    netProfit: "ប្រាក់ចំណេញសុទ្ធ",

    // Inventory
    storageStatus: "ស្ថានភាពគ្រឿងបញ្ចាំ",
    warehouse: "ឃ្លាំង/បន្ទប់សុវត្ថិភាព",
    itemHistory: "សៀវភៅតាមដានទំនិញ",
    InStorage: "កំពុងរក្សាទុកក្នុងទូដែក",
    Released: "បានលោះចេញវិញរួចរាល់",
    Auction: "គ្រឿងបញ្ចាំដាក់លក់ឡៃឡុង",
    Lost: "ទំនិញដែលបាត់បង់/សំណង",

    // Notifications
    reminderAlerts: "ការផ្ញើសាររំលឹកបង់ប្រាក់",
    dueReminder: "រំលឹកមុនថ្ងៃបង់",
    overdueReminder: "រំលឹកពេលយឺតយ៉ាវ",
    channels: "ប្រព័ន្ធបញ្ជូនសារ",
    sendNotification: "ផ្ញើសារជូនដំណឹងភ្លាមៗ",
    telegram: "សារទៅកាន់ Telegram Bot",
    sms: "សារទូរស័ព្ទដៃ (SMS Cell)",
    email: "អ៊ីមែលជូនដំណឹង (Email)",

    // Users
    userManagement: "ការគ្រប់គ្រងបុគ្គលិក និងសិទ្ធិប្រើប្រាស់",
    users: "គណនីបុគ្គលិកប្រើប្រាស់",
    roles: "អ្នកគ្រប់គ្រង និងតួនាទី",
    activityLogs: "កំណត់ត្រាសកម្មភាពសន្តិសុខ",
    permissionList: "តារាងបែងចែកសិទ្ធិបញ្ជា",
    SuperAdmin: "អគ្គនាយក (Super Admin)",
    Admin: "អ្នកគ្រប់គ្រងប្រព័ន្ធ (Admin)",
    Manager: "ប្រធានសាខា (Branch Manager)",
    Staff: "បុគ្គលិកបញ្ជរ (Staff)",
    Accountant: "បុគ្គលិកគណនេយ្យ (Accountant)",

    // Settings
    companySettings: "ការកំណត់ព័ត៌មានក្រុមហ៊ុន និងអត្រាហិរញ្ញវត្ថុ",
    companyName: "ឈ្មោះគ្រឹះស្ថាន/ហាង",
    addressKh: "អាសយដ្ឋាន (ភាសាខ្មែរ)",
    addressEn: "អាសយដ្ឋាន (ភាសាអង់គ្លេស)",
    phoneSetting: "លេខទូរស័ព្ទផ្លូវការ",
    emailSetting: "អ៊ីមែលផ្លូវការ",
    defaultInterestRate: "អត្រាការប្រាក់ទូទៅ (%/ខែ)",
    penaltyRate: "ប្រាក់ពិន័យយឺតយ៉ាវ (%/ថ្ងៃ)",
    dualCurrency: "រូបិយប័ណ្ណទូទាត់ (ដុល្លារ/រៀល)",
    taxRate: "អត្រាពន្ធសហគ្រាស (%)",
    branchName: "ឈ្មោះសាខាប្រតិបត្តិការ",
    backupDb: "ចម្លងទិន្នន័យប្រព័ន្ធទុក (Backup)",
    restoreDb: "ទាញយកទិន្នន័យចាស់មកវិញ (Restore)",
  }
};
